/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Disband,
    DisbandFromJSON,
    DisbandFromJSONTyped,
    DisbandToJSON,
} from './Disband';

/**
 * 
 * @export
 * @interface Alarm
 */
export interface Alarm {
    /**
     * 
     * @type {string}
     * @memberof Alarm
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof Alarm
     */
    date?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Alarm
     */
    isRepetition?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Alarm
     */
    repetitionWeekDays?: string;
    /**
     * 
     * @type {Disband}
     * @memberof Alarm
     */
    disband?: Disband;
}

export function AlarmFromJSON(json: any): Alarm {
    return AlarmFromJSONTyped(json, false);
}

export function AlarmFromJSONTyped(json: any, ignoreDiscriminator: boolean): Alarm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'isRepetition': !exists(json, 'isRepetition') ? undefined : json['isRepetition'],
        'repetitionWeekDays': !exists(json, 'repetitionWeekDays') ? undefined : json['repetitionWeekDays'],
        'disband': !exists(json, 'disband') ? undefined : DisbandFromJSON(json['disband']),
    };
}

export function AlarmToJSON(value?: Alarm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'date': value.date,
        'isRepetition': value.isRepetition,
        'repetitionWeekDays': value.repetitionWeekDays,
        'disband': DisbandToJSON(value.disband),
    };
}

