/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Alarm object
 * @export
 * @interface AlarmDTO
 */
export interface AlarmDTO {
    /**
     * 
     * @type {number}
     * @memberof AlarmDTO
     */
    date: number;
    /**
     * 
     * @type {boolean}
     * @memberof AlarmDTO
     */
    isRepetition: boolean;
    /**
     * 
     * @type {string}
     * @memberof AlarmDTO
     */
    repetitionWeekDays?: string;
    /**
     * 
     * @type {string}
     * @memberof AlarmDTO
     */
    disbandId: string;
}

export function AlarmDTOFromJSON(json: any): AlarmDTO {
    return AlarmDTOFromJSONTyped(json, false);
}

export function AlarmDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlarmDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': json['date'],
        'isRepetition': json['isRepetition'],
        'repetitionWeekDays': !exists(json, 'repetitionWeekDays') ? undefined : json['repetitionWeekDays'],
        'disbandId': json['disbandId'],
    };
}

export function AlarmDTOToJSON(value?: AlarmDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': value.date,
        'isRepetition': value.isRepetition,
        'repetitionWeekDays': value.repetitionWeekDays,
        'disbandId': value.disbandId,
    };
}

