/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Oxygen,
    OxygenFromJSON,
    OxygenFromJSONTyped,
    OxygenToJSON,
} from './Oxygen';

/**
 * 
 * @export
 * @interface MeasureResponseOxygen
 */
export interface MeasureResponseOxygen {
    /**
     * 
     * @type {Array<Oxygen>}
     * @memberof MeasureResponseOxygen
     */
    measures?: Array<Oxygen>;
    /**
     * 
     * @type {number}
     * @memberof MeasureResponseOxygen
     */
    minMeasure?: number;
    /**
     * 
     * @type {number}
     * @memberof MeasureResponseOxygen
     */
    maxMeasure?: number;
}

export function MeasureResponseOxygenFromJSON(json: any): MeasureResponseOxygen {
    return MeasureResponseOxygenFromJSONTyped(json, false);
}

export function MeasureResponseOxygenFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasureResponseOxygen {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'measures': !exists(json, 'measures') ? undefined : ((json['measures'] as Array<any>).map(OxygenFromJSON)),
        'minMeasure': !exists(json, 'minMeasure') ? undefined : json['minMeasure'],
        'maxMeasure': !exists(json, 'maxMeasure') ? undefined : json['maxMeasure'],
    };
}

export function MeasureResponseOxygenToJSON(value?: MeasureResponseOxygen | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'measures': value.measures === undefined ? undefined : ((value.measures as Array<any>).map(OxygenToJSON)),
        'minMeasure': value.minMeasure,
        'maxMeasure': value.maxMeasure,
    };
}

