/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Measure object
 * @export
 * @interface MeasureDTO
 */
export interface MeasureDTO {
    /**
     * 
     * @type {number}
     * @memberof MeasureDTO
     */
    data?: number;
    /**
     * 
     * @type {number}
     * @memberof MeasureDTO
     */
    date?: number;
    /**
     * 
     * @type {string}
     * @memberof MeasureDTO
     */
    disbandMac: string;
}

export function MeasureDTOFromJSON(json: any): MeasureDTO {
    return MeasureDTOFromJSONTyped(json, false);
}

export function MeasureDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasureDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'disbandMac': json['disbandMac'],
    };
}

export function MeasureDTOToJSON(value?: MeasureDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'date': value.date,
        'disbandMac': value.disbandMac,
    };
}

