/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Temperature,
    TemperatureFromJSON,
    TemperatureFromJSONTyped,
    TemperatureToJSON,
} from './Temperature';

/**
 * 
 * @export
 * @interface MeasureResponseTemperature
 */
export interface MeasureResponseTemperature {
    /**
     * 
     * @type {Array<Temperature>}
     * @memberof MeasureResponseTemperature
     */
    measures?: Array<Temperature>;
    /**
     * 
     * @type {number}
     * @memberof MeasureResponseTemperature
     */
    minMeasure?: number;
    /**
     * 
     * @type {number}
     * @memberof MeasureResponseTemperature
     */
    maxMeasure?: number;
}

export function MeasureResponseTemperatureFromJSON(json: any): MeasureResponseTemperature {
    return MeasureResponseTemperatureFromJSONTyped(json, false);
}

export function MeasureResponseTemperatureFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasureResponseTemperature {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'measures': !exists(json, 'measures') ? undefined : ((json['measures'] as Array<any>).map(TemperatureFromJSON)),
        'minMeasure': !exists(json, 'minMeasure') ? undefined : json['minMeasure'],
        'maxMeasure': !exists(json, 'maxMeasure') ? undefined : json['maxMeasure'],
    };
}

export function MeasureResponseTemperatureToJSON(value?: MeasureResponseTemperature | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'measures': value.measures === undefined ? undefined : ((value.measures as Array<any>).map(TemperatureToJSON)),
        'minMeasure': value.minMeasure,
        'maxMeasure': value.maxMeasure,
    };
}

