/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Pressure,
    PressureFromJSON,
    PressureFromJSONTyped,
    PressureToJSON,
} from './Pressure';

/**
 * 
 * @export
 * @interface MeasureResponsePressure
 */
export interface MeasureResponsePressure {
    /**
     * 
     * @type {Array<Pressure>}
     * @memberof MeasureResponsePressure
     */
    measures?: Array<Pressure>;
    /**
     * 
     * @type {number}
     * @memberof MeasureResponsePressure
     */
    minMeasure?: number;
    /**
     * 
     * @type {number}
     * @memberof MeasureResponsePressure
     */
    maxMeasure?: number;
}

export function MeasureResponsePressureFromJSON(json: any): MeasureResponsePressure {
    return MeasureResponsePressureFromJSONTyped(json, false);
}

export function MeasureResponsePressureFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeasureResponsePressure {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'measures': !exists(json, 'measures') ? undefined : ((json['measures'] as Array<any>).map(PressureFromJSON)),
        'minMeasure': !exists(json, 'minMeasure') ? undefined : json['minMeasure'],
        'maxMeasure': !exists(json, 'maxMeasure') ? undefined : json['maxMeasure'],
    };
}

export function MeasureResponsePressureToJSON(value?: MeasureResponsePressure | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'measures': value.measures === undefined ? undefined : ((value.measures as Array<any>).map(PressureToJSON)),
        'minMeasure': value.minMeasure,
        'maxMeasure': value.maxMeasure,
    };
}

