/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Disband,
    DisbandFromJSON,
    DisbandFromJSONTyped,
    DisbandToJSON,
} from './Disband';

/**
 * 
 * @export
 * @interface Oxygen
 */
export interface Oxygen {
    /**
     * 
     * @type {string}
     * @memberof Oxygen
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof Oxygen
     */
    data?: number;
    /**
     * 
     * @type {number}
     * @memberof Oxygen
     */
    date?: number;
    /**
     * 
     * @type {Disband}
     * @memberof Oxygen
     */
    disband?: Disband;
}

export function OxygenFromJSON(json: any): Oxygen {
    return OxygenFromJSONTyped(json, false);
}

export function OxygenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Oxygen {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'data': !exists(json, 'data') ? undefined : json['data'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'disband': !exists(json, 'disband') ? undefined : DisbandFromJSON(json['disband']),
    };
}

export function OxygenToJSON(value?: Oxygen | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'data': value.data,
        'date': value.date,
        'disband': DisbandToJSON(value.disband),
    };
}

