/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Disorder object
 * @export
 * @interface DisorderDTO
 */
export interface DisorderDTO {
    /**
     * 
     * @type {string}
     * @memberof DisorderDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof DisorderDTO
     */
    observations?: string;
}

export function DisorderDTOFromJSON(json: any): DisorderDTO {
    return DisorderDTOFromJSONTyped(json, false);
}

export function DisorderDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisorderDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'observations': !exists(json, 'observations') ? undefined : json['observations'],
    };
}

export function DisorderDTOToJSON(value?: DisorderDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'observations': value.observations,
    };
}

