/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Disorder
 */
export interface Disorder {
    /**
     * 
     * @type {string}
     * @memberof Disorder
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Disorder
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Disorder
     */
    observations?: string;
}

export function DisorderFromJSON(json: any): Disorder {
    return DisorderFromJSONTyped(json, false);
}

export function DisorderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Disorder {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'observations': !exists(json, 'observations') ? undefined : json['observations'],
    };
}

export function DisorderToJSON(value?: Disorder | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'observations': value.observations,
    };
}

