/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Subject,
    SubjectFromJSON,
    SubjectFromJSONTyped,
    SubjectToJSON,
} from './Subject';
import {
    UserModel,
    UserModelFromJSON,
    UserModelFromJSONTyped,
    UserModelToJSON,
} from './UserModel';

/**
 * 
 * @export
 * @interface Homework
 */
export interface Homework {
    /**
     * 
     * @type {string}
     * @memberof Homework
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Homework
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Homework
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof Homework
     */
    deadline?: number;
    /**
     * 
     * @type {Subject}
     * @memberof Homework
     */
    subject?: Subject;
    /**
     * 
     * @type {UserModel}
     * @memberof Homework
     */
    user?: UserModel;
}

export function HomeworkFromJSON(json: any): Homework {
    return HomeworkFromJSONTyped(json, false);
}

export function HomeworkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Homework {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'deadline': !exists(json, 'deadline') ? undefined : json['deadline'],
        'subject': !exists(json, 'subject') ? undefined : SubjectFromJSON(json['subject']),
        'user': !exists(json, 'user') ? undefined : UserModelFromJSON(json['user']),
    };
}

export function HomeworkToJSON(value?: Homework | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'deadline': value.deadline,
        'subject': SubjectToJSON(value.subject),
        'user': UserModelToJSON(value.user),
    };
}

