/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * School year object
 * @export
 * @interface SchoolYearDTO
 */
export interface SchoolYearDTO {
    /**
     * 
     * @type {string}
     * @memberof SchoolYearDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SchoolYearDTO
     */
    study?: string;
}

export function SchoolYearDTOFromJSON(json: any): SchoolYearDTO {
    return SchoolYearDTOFromJSONTyped(json, false);
}

export function SchoolYearDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchoolYearDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'study': !exists(json, 'study') ? undefined : json['study'],
    };
}

export function SchoolYearDTOToJSON(value?: SchoolYearDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'study': value.study,
    };
}

