/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Timetable object
 * @export
 * @interface TimetableDTO
 */
export interface TimetableDTO {
    /**
     * 
     * @type {string}
     * @memberof TimetableDTO
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof TimetableDTO
     */
    endTime?: string;
    /**
     * 
     * @type {number}
     * @memberof TimetableDTO
     */
    weekDay?: number;
    /**
     * 
     * @type {string}
     * @memberof TimetableDTO
     */
    subjectId?: string;
    /**
     * 
     * @type {string}
     * @memberof TimetableDTO
     */
    userId?: string;
}

export function TimetableDTOFromJSON(json: any): TimetableDTO {
    return TimetableDTOFromJSONTyped(json, false);
}

export function TimetableDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimetableDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startTime': !exists(json, 'startTime') ? undefined : json['startTime'],
        'endTime': !exists(json, 'endTime') ? undefined : json['endTime'],
        'weekDay': !exists(json, 'weekDay') ? undefined : json['weekDay'],
        'subjectId': !exists(json, 'subjectId') ? undefined : json['subjectId'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function TimetableDTOToJSON(value?: TimetableDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startTime': value.startTime,
        'endTime': value.endTime,
        'weekDay': value.weekDay,
        'subjectId': value.subjectId,
        'userId': value.userId,
    };
}

