/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * User object
 * @export
 * @interface UpdateUserDTO
 */
export interface UpdateUserDTO {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDTO
     */
    surname?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDTO
     */
    birthday?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDTO
     */
    email?: string;
}

export function UpdateUserDTOFromJSON(json: any): UpdateUserDTO {
    return UpdateUserDTOFromJSONTyped(json, false);
}

export function UpdateUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'birthday': !exists(json, 'birthday') ? undefined : json['birthday'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function UpdateUserDTOToJSON(value?: UpdateUserDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'surname': value.surname,
        'birthday': value.birthday,
        'email': value.email,
    };
}

