/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * User object
 * @export
 * @interface UserDTO
 */
export interface UserDTO {
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    surname?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    birthday?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserDTO
     */
    isDisorder?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    role?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    disorderId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    schoolYearId?: string;
}

export function UserDTOFromJSON(json: any): UserDTO {
    return UserDTOFromJSONTyped(json, false);
}

export function UserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'surname': !exists(json, 'surname') ? undefined : json['surname'],
        'birthday': !exists(json, 'birthday') ? undefined : json['birthday'],
        'isDisorder': !exists(json, 'isDisorder') ? undefined : json['isDisorder'],
        'email': json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'role': !exists(json, 'role') ? undefined : json['role'],
        'disorderId': !exists(json, 'disorderId') ? undefined : json['disorderId'],
        'schoolYearId': !exists(json, 'schoolYearId') ? undefined : json['schoolYearId'],
    };
}

export function UserDTOToJSON(value?: UserDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'surname': value.surname,
        'birthday': value.birthday,
        'isDisorder': value.isDisorder,
        'email': value.email,
        'password': value.password,
        'role': value.role,
        'disorderId': value.disorderId,
        'schoolYearId': value.schoolYearId,
    };
}

