/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Disbeac object
 * @export
 * @interface DisbeacDTO
 */
export interface DisbeacDTO {
    /**
     * 
     * @type {string}
     * @memberof DisbeacDTO
     */
    mac: string;
    /**
     * 
     * @type {string}
     * @memberof DisbeacDTO
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof DisbeacDTO
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof DisbeacDTO
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof DisbeacDTO
     */
    userId: string;
}

export function DisbeacDTOFromJSON(json: any): DisbeacDTO {
    return DisbeacDTOFromJSONTyped(json, false);
}

export function DisbeacDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DisbeacDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mac': json['mac'],
        'model': json['model'],
        'version': json['version'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'userId': json['userId'],
    };
}

export function DisbeacDTOToJSON(value?: DisbeacDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mac': value.mac,
        'model': value.model,
        'version': value.version,
        'date': value.date,
        'userId': value.userId,
    };
}

