/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Disbeac
 */
export interface Disbeac {
    /**
     * 
     * @type {string}
     * @memberof Disbeac
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Disbeac
     */
    mac?: string;
    /**
     * 
     * @type {string}
     * @memberof Disbeac
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof Disbeac
     */
    version?: string;
    /**
     * 
     * @type {number}
     * @memberof Disbeac
     */
    date?: number;
    /**
     * 
     * @type {string}
     * @memberof Disbeac
     */
    userId?: string;
}

export function DisbeacFromJSON(json: any): Disbeac {
    return DisbeacFromJSONTyped(json, false);
}

export function DisbeacFromJSONTyped(json: any, ignoreDiscriminator: boolean): Disbeac {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'mac': !exists(json, 'mac') ? undefined : json['mac'],
        'model': !exists(json, 'model') ? undefined : json['model'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function DisbeacToJSON(value?: Disbeac | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'mac': value.mac,
        'model': value.model,
        'version': value.version,
        'date': value.date,
        'userId': value.userId,
    };
}

