/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandledResponse
 */
export interface HandledResponse {
    /**
     * 
     * @type {string}
     * @memberof HandledResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof HandledResponse
     */
    number?: number;
}

export function HandledResponseFromJSON(json: any): HandledResponse {
    return HandledResponseFromJSONTyped(json, false);
}

export function HandledResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandledResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'number': !exists(json, 'number') ? undefined : json['number'],
    };
}

export function HandledResponseToJSON(value?: HandledResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'number': value.number,
    };
}

