/* tslint:disable */
/* eslint-disable */
/**
 * Disheap Service
 * Disheap API connection to Disbands and Disbeacs information
 *
 * The version of the OpenAPI document: v0.0.1
 * Contact: ire.cunba@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Disbeac ID
 * @export
 * @interface LocationDTO
 */
export interface LocationDTO {
    /**
     * 
     * @type {number}
     * @memberof LocationDTO
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationDTO
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof LocationDTO
     */
    date?: number;
    /**
     * 
     * @type {string}
     * @memberof LocationDTO
     */
    disbeacMac?: string;
}

export function LocationDTOFromJSON(json: any): LocationDTO {
    return LocationDTOFromJSONTyped(json, false);
}

export function LocationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'disbeacMac': !exists(json, 'disbeacMac') ? undefined : json['disbeacMac'],
    };
}

export function LocationDTOToJSON(value?: LocationDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latitude': value.latitude,
        'longitude': value.longitude,
        'date': value.date,
        'disbeacMac': value.disbeacMac,
    };
}

